---
# tasks file for ssh

- name: Install openssh (Ubuntu/Debian)
  apt:
    name: openssh-client
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install openssh (Arch)
  pacman:
    name: openssh-client
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'
