---
# tasks file for git

- name: Install git (Ubuntu/Debian)
  apt:
    name: git
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install git (Arch)
  yay:
    name: git
    state: latest
  when: ansible_distribution == 'Archlinux'

- name: Check if git config exists
  stat:
    path: "/home/{{ target_user }}/.gitconfig"
  register: gitconfig_file
  changed_when: false

- name: Moving existing gitconfig to .gitconfig.backup
  command: mv "/home/{{ target_user }}/.gitconfig" "/home/{{ target_user }}/.gitconfig.backup"
  when: gitconfig_file.stat.exists and gitconfig_file.stat.islnk is defined and gitconfig_file.stat.islnk == False

- name: Link gitconfig
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: "/home/{{ target_user }}/.gitconfig"
    state: link
  