---
# tasks file for git

- name: Install git (Ubuntu/Debian)
  apt:
    name: git
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Install git (Arch)
  pacman:
    name: git
    state: latest
  when: ansible_distribution == 'Archlinux'

- name: Remove existing .gitconfig 
  file:
    path: "/home/{{ target_user }}/.gitconfig"
    state: absent

- name: Link gitconfig
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: "/home/{{ target_user }}/.gitconfig"
    state: link
