---
# tasks file for tmux

- name: Install tmux (Ubuntu/Debian)
  apt:
    name: tmux
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install tmux (Arch)
  pacman:
    name: tmux
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: Create symlink config
  file: 
    src: "{{ role_path }}/files/tmux.conf"
    dest: "/home/{{ target_user }}/.tmux.conf"
    state: link

- name: Check for systemd user directory
  stat:
    path: "/home/{{ target_user }}/.config/systemd/user"
  register: systemd_user_directory

- name: Create systemd user directory
  file:
    path: "/home/{{ target_user }}/.config/systemd/user"
    state: directory 
    recurse: true
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755
  when: not systemd_user_directory.stat.exists

- name: Create symlink tmux systemd service 
  file: 
    src: "{{ role_path }}/files/tmux.service"
    dest: "/home/{{ target_user }}/.config/systemd/user/tmux.service"
    state: link

- name: "Find uid of user"
  command: "id -u {{ target_user }}"
  register: target_user_id
  check_mode: no
  changed_when: false

- name: "Determine XDG_RUNTIME_DIR"
  set_fact:
    xdg_runtime_dir: "/run/user/{{ target_user_id.stdout }}"
  changed_when: false

- name: Start tmux
  become: true
  become_user: "{{ target_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: tmux.service
    daemon_reload: true
    state: restarted 
    scope: user