---
# tasks file for neovim

- name: Install neovim (Ubuntu/Debian)
  apt:
    name: neovim
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install neovim (Arch)
  yay:
    name: neovim
    state: latest
  when: ansible_distribution == 'Archlinux'

- name: Check if nvim config folder exists 
  stat:
    path: "/home/{{ target_user }}/.config/nvim"
  register: nvim_config_folder

- name: Print debug message
  ansible.builtin.debug:
    msg: "Path exists and isn't a symlink"
  when: nvim_config_folder.stat.islnk is defined and nvim_config_folder.stat.islnk == False

- name: Moving existing folder to nvim_backup
  command: mv "/home/{{ target_user }}/.config/nvim" "/home/{{ target_user }}/.config/nvim_backup"
  when: nvim_config_folder.stat.exists and nvim_config_folder.stat.islnk is defined and nvim_config_folder.stat.islnk == False
  
- name: Create symlink for nvim 
  file:
    src: "{{ role_path }}/files/nvim"
    dest: "/home/{{ target_user }}/.config/nvim"
    state: link
